name: CI docker container

on:
  workflow_call:
      inputs:
        CALLER_REPOSITORY:
          required: true
          type: string
        CALLER_REPOSITORY_VERSION:
          required: true
          type: string
        REGISTRY:
          required: true
          type: string
        DOCKERFILE:
          required: true
          type: string
        PLATFORMS:
          required: true
          type: string
        RUNS_ON:
          required: true
          type: string
      secrets:
        GIT_USERNAME:
          required: true
        GIT_TOKEN:
          required: true
        GITLAB_PACKAGES_TOKEN:
          required: true
        REGISTRY_LOGIN:
          required: true
        REGISTRY_PASSWORD:
          required: true
        GITLAB_TOKEN:
          required: true
        GITLAB_URL:
          required: true
        GITLAB_REPOSITORY:
          required: true

jobs:
  publish-images:
    timeout-minutes: 60
    runs-on: ${{ inputs.RUNS_ON }}
    permissions:
      packages: write
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.CALLER_REPOSITORY }}
          ref: ${{ inputs.CALLER_REPOSITORY_VERSION }}
          token: ${{ secrets.GIT_TOKEN }}

      - name: Checkout Modino-io/modino-devops repository
        uses: actions/checkout@v3
        with:
          repository: Modino-io/modino-devops
          path: modino-devops
          token: ${{ secrets.GIT_TOKEN }}

      - name: Prepare Certs
        run: |
          ./modino-devops/docker-image-script/getCerts.sh
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_URL: ${{ secrets.GITLAB_URL }}
          GITLAB_REPOSITORY: ${{ secrets.GITLAB_REPOSITORY }}

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ inputs.REGISTRY }}/modino/modino/${{ inputs.CALLER_REPOSITORY }}
          tags: |
            type=sha,priority=900,prefix=build-${{ github.run_id }}-

      - name: Docker build and push
        id: docker_build_push
        run: |
          docker build \
          -t ${{ steps.meta.outputs.labels }}:${{ steps.meta.outputs.tags }} \
          --build-arg GITHUB_USERNAME=${{ secrets.GIT_USERNAME }} \
          --build-arg GITHUB_TOKEN=${{ secrets.GIT_TOKEN }} \
          --build-arg GITLAB_PACKAGES_TOKEN=${{ secrets.GIT_TOKEN }} \
          --build-arg TARGETPLATFORM=${{ inputs.PLATFORMS }} \
          -f ./Dockerfile_online .

          docker push ${{ steps.meta.outputs.labels }}:${{ steps.meta.outputs.tags }}
