name: CI docker container

workflow_call:
    inputs:
      CALLER_REPOSITORY:
        required: true
        type: string
      CALLER_REPOSITORY_VERSION:
        required: true
        type: string
      MODINO_DEVOPS_VERSION:
        required: true
        type: string
      REGISTRY:
        required: true
        type: string
    secrets:
      GIT_USERNAME:
        required: true
      GIT_TOKEN:
        required: true
      GITLAB_PACKAGES_TOKEN:
        required: true
      REGISTRY_LOGIN:
        required: true
      REGISTRY_PASSWORD:
        required: true
      GITLAB_TOKEN:
        required: true

jobs:
  publish-packages:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Modino-io/modino-devops repository
        uses: actions/checkout@v2
        with:
          repository: Modino-io/modino-devops
          path: modino-devops
          ref: ${{ inputs.MODINO_DEVOPS_VERSION }}
          token: ${{ secrets.GIT_TOKEN }}

      - name: Checkout caller repository
        uses: actions/checkout@v2
        with:
          repository: Modino-io/${{ inputs.CALLER_REPOSITORY }}
          path: ${{ inputs.CALLER_REPOSITORY }}
          ref: ${{ inputs.CALLER_REPOSITORY_VERSION }}
          token: ${{ secrets.GIT_TOKEN }}

      - name: Prepare Certs
        run: |
          ./modino-devops/container-scripts/getCerts.sh
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          CALLER_REPOSITORY: ${{ inputs.CALLER_REPOSITORY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=auto
          images: |
            ${{ inputs.REGISTRY }}/modino/modino/${{ inputs.CALLER_REPOSITORY }}
          tags: |
            type=raw,priority=800,value={{branch}}-${{ github.run_id }}
            type=sha,priority=900,prefix={{branch}}-
            type=semver,priority=1000,pattern={{version}},prefix=main-,

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          file: ./Dockerfile_online
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GITLAB_PACKAGES_TOKEN=${{ secrets.GITLAB_PACKAGES_TOKEN }}
            GITHUB_USERNAME=${{ secrets.GIT_USERNAME }}
            GITHUB_TOKEN=${{ secrets.GIT_TOKEN }}
