name: CI docker container

on:
  workflow_call:
      inputs:
        CALLER_REPOSITORY:
          required: true
          type: string
        CALLER_REPOSITORY_VERSION:
          required: true
          type: string
        REGISTRY:
          required: true
          type: string
        DOCKERFILE:
          required: true
          type: string
        PLATFORMS:
          required: true
          type: string
        RUNS_ON:
          required: true
          type: string
      secrets:
        MODINO_CI_GITHUB_TOKEN:
          required: true

jobs:
  publish-images:
    timeout-minutes: 60
    runs-on: ${{ inputs.RUNS_ON }}
    permissions:
      packages: write
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.CALLER_REPOSITORY }}
          ref: ${{ inputs.CALLER_REPOSITORY_VERSION }}
          token: ${{ secrets.MODINO_CI_GITHUB_TOKEN }}

      - name: Checkout Modino-io/modino-devops repository
        uses: actions/checkout@v3
        with:
          repository: Modino-io/modino-devops
          path: modino-devops
          token: ${{ secrets.MODINO_CI_GITHUB_TOKEN }}

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.test.modino.cloud/
          method: github
          githubToken: ${{ secrets.MODINO_CI_GITHUB_TOKEN }}
          tlsSkipVerify: true
          secrets: |
            kv/data/modino-tokens RSA_PUB_PEM | RSA_PUB_PEM ;
            kv/data/modino-tokens PASSWD | PASSWD ;
            kv/data/modino-tokens KEY_ASC | KEY_ASC ;
            kv/data/modino-ci-secrets MODINO_CI_GITHUB_USERNAME | MODINO_CI_GITHUB_USERNAME ;
            kv/data/modino-ci-secrets MODINO_CI_GITLAB_USERNAME | MODINO_CI_GITLAB_USERNAME ;
            kv/data/modino-ci-secrets MODINO_CI_GITLAB_TOKEN | MODINO_CI_GITLAB_TOKEN ;
            kv/data/modino-ci-secrets MODINO_CI_GITLAB_USERNAME | REGISTRY_LOGIN ;
            kv/data/modino-ci-secrets MODINO_CI_GITLAB_TOKEN | REGISTRY_PASSWORD ;
            kv/data/modino-ci-secrets MODINO_GITLAB_URL | MODINO_GITLAB_URL ;
            kv/data/modino-ci-secrets MODINO_GITLAB_CERTS_REPOSITORY | MODINO_GITLAB_CERTS_REPOSITORY ;

      - name: Setup secret files
        run: |
          echo '${{ steps.secrets.outputs.RSA_PUB_PEM }}' | base64 --decode > rsa_pub.pem
          echo '${{ steps.secrets.outputs.PASSWD }}' > passwd
          echo '${{ steps.secrets.outputs.KEY_ASC }}' | base64 --decode > key.asc

      - name: Prepare Certs
        run: |
          ./modino-devops/docker-image-script/getCerts.sh
        env:
          MODINO_CI_GITLAB_TOKEN: '${{ steps.secrets.outputs.MODINO_CI_GITLAB_TOKEN }}'
          MODINO_GITLAB_URL: '${{ steps.secrets.outputs.MODINO_GITLAB_URL }}'
          MODINO_GITLAB_CERTS_REPOSITORY: '${{ steps.secrets.outputs.MODINO_GITLAB_CERTS_REPOSITORY }}'

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ steps.secrets.outputs.REGISTRY_LOGIN }}
          password: ${{ steps.secrets.outputs.REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ inputs.REGISTRY }}/modino/modino/${{ inputs.CALLER_REPOSITORY }}
          tags: |
            type=sha,priority=900,prefix=build-${{ github.run_id }}-

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          platforms: ${{ inputs.PLATFORMS }}
          file: ./${{ inputs.DOCKERFILE }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            MODINO_CI_GITLAB_TOKEN=${{ steps.secrets.outputs.MODINO_CI_GITLAB_TOKEN }}
            MODINO_CI_GITHUB_USERNAME=${{ steps.secrets.outputs.MODINO_CI_GITHUB_USERNAME }}
            MODINO_CI_GITHUB_TOKEN=${{ secrets.MODINO_CI_GITHUB_TOKEN }}
