name: Determinate runner

on:
  workflow_call:
    outputs:
      machine:
        value: ${{ jobs.machine.outputs.machine }}

jobs:
  machine:
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    outputs:
      machine: ${{ steps.machine.outputs.machine }}
    steps:
      - id: machine
        name: Determanate runner
        shell: bash
        run: |
          success=0
          for x in $webhook_servers; do
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null "$x")
          if [ $response = 200 ]; then
              success=$((success+1))
          fi
          done
          if [ $success -gt 0 ]; then
              echo "machine=mac-mini"
              exit 0
          fi
              echo "machine=ubuntu-20.04"
              exit 0
        env:
          webhook_servers: https://98.arm.runners.modino.dev/
