name: Determinate runner

on:
  workflow_call:
    inputs:
        RUNNER_ARCHITECTURE:
          required: true
          type: string
    outputs:
      machine:
        value: ${{ jobs.machine.outputs.machine }}

jobs:
  machine:
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    outputs:
      machine: ${{ steps.machine.outputs.machine }}
    steps:
      - id: machine
        name: Determanate runner
        shell: bash
        run: |

          success=0
          if [ "${{ inputs.RUNNER_ARCHITECTURE }}" = "self-hosted-amd" ]; then
            export WEBHOOK_SERVERS=$amd_webhook_servers
          elif [ "${{ inputs.RUNNER_ARCHITECTURE }}" = "self-hosted-arm" ]; then
            export WEBHOOK_SERVERS=$arm_webhook_servers
          elif [ "${{ inputs.RUNNER_ARCHITECTURE }}" = "self-hosted" ]; then
            export WEBHOOK_SERVERS="$amd_webhook_servers $arm_webhook_servers"
          else
            echo "machine=ubuntu-20.04" >> $GITHUB_OUTPUT
            exit 0
          fi

          for x in $WEBHOOK_SERVERS; do
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null "$x")
          if [ $response = 200 ]; then
              success=$((success+1))
          fi
          done
          if [ $success -gt 0 ]; then
              echo machine=${{ inputs.RUNNER_ARCHITECTURE }} >> $GITHUB_OUTPUT
              exit 0
          fi
              echo "machine=ubuntu-20.04" >> $GITHUB_OUTPUT
              exit 0
        env:
          arm_webhook_servers: "https://98.arm.runners.modino.dev/"
          amd_webhook_servers: "https://99.x86.runners.modino.dev/"
