name: Determinate runner

on:
  workflow_call:
    outputs:
      machine:
        value: ${{ jobs.machine.outputs.machine }}

jobs:
  machine:
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    outputs:
      machine: ${{ steps.machine.outputs.machine }}
    steps:
      - id: machine
        name: Determanate runner
        shell: bash
        run: |
          echo "machine=k8s-vm" >> $GITHUB_OUTPUT
